# Site settings
baseurl = "https://indeyets.ru/"
languageCode = "ru-ru"
title = "Алексей Захлестин"
theme = "mini"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
disqusShortname = "indeyets"

[params]
	name = "Алексей Захлестин"
	description = "Describe your website"
	bio = "indeyets"
	# Enter optionally your twitter account
	twitter = "indeyets"
	enableRSS = true

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = " На главную!"
	subscribe = "Подпишись через RSS"
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = "© Все права защищены 2011–2021. Алексей Захлестин"
	# Sharing options and author information in posts
	aboutAuthor = "It's OK!"
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "mono-social"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    # fivehundredpx = "https://500px.com/indeyets"
    # friendsfeed = "https://freefeed.net/indeyets"
    # facebook = "https://facebook.com/indeyets"
    github   = "https://github.com/indeyets"
